# Generated by Django 5.1.1 on 2024-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('ultra-rare', 'Ultra Rare')], default='common', max_length=50)),
            ],
        ),
    ]
